<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Client;

class ClientSeeder extends Seeder
{
    public function run(): void
    {

        $clients = [
            ["id" => "1","name" => "Agus Pojok","alamat" => "Jl. Melati No. 35","type" => "Peternak","keterangan" => "Elf"],
            ["id" => "2","name" => "Bonari","alamat" => "Jl. Melati No. 4","type" => "Peternak","keterangan" => "Elf"],
            ["id" => "3","name" => "Iwan Dawung","alamat" => "Jl. Melati No. 46","type" => "Peternak","keterangan" => "Elf"],
            ["id" => "4","name" => "Nunuk","alamat" => "Jl. Melati No. 3","type" => "Peternak","keterangan" => "Elf"],
            ["id" => "5","name" => "Candra","alamat" => "Jl. Melati No. 45","type" => "Peternak","keterangan" => "Elf"],
            ["id" => "6","name" => "Eko Bedali","alamat" => "Jl. Melati No. 1","type" => "Peternak","keterangan" => "Elf"],
            ["id" => "7","name" => "Kusnar","alamat" => "Jl. Melati No. 37","type" => "Peternak","keterangan" => "Elf"],
            ["id" => "8","name" => "Jainal Candirejo","alamat" => "Jl. Melati No. 29","type" => "Peternak","keterangan" => "Elf"],
            ["id" => "9","name" => "Cahyo","alamat" => "Jl. Melati No. 8","type" => "Peternak","keterangan" => "Elf"],
            ["id" => "10","name" => "Unsu","alamat" => "Jl. Melati No. 12","type" => "Peternak","keterangan" => "Merah"],
            ["id" => "11","name" => "Kusuma","alamat" => "Jl. Melati No. 49","type" => "Peternak","keterangan" => "Elf"],
            ["id" => "12","name" => "Sutik Candirejo","alamat" => "Jl. Melati No. 40","type" => "Peternak","keterangan" => "Elf"],
            ["id" => "13","name" => "Maria","alamat" => "Jl. Melati No. 33","type" => "Peternak","keterangan" => "Elf"],
            ["id" => "14","name" => "Suryanto","alamat" => "Jl. Melati No. 49","type" => "Peternak","keterangan" => "Elf"],
            ["id" => "15","name" => "Sigit","alamat" => "Jl. Melati No. 11","type" => "Peternak","keterangan" => "Elf"],
            ["id" => "16","name" => "Musid","alamat" => "Jl. Melati No. 44","type" => "Peternak","keterangan" => "Elf"],
            ["id" => "17","name" => "Sugeng Krebet","alamat" => "Jl. Melati No. 3","type" => "Peternak","keterangan" => "Elf"],
            ["id" => "18","name" => "Diki","alamat" => "Jl. Melati No. 29","type" => "Peternak","keterangan" => "Elf"],
            ["id" => "19","name" => "Sugeng","alamat" => "Jl. Melati No. 36","type" => "Peternak","keterangan" => "Elf"],
            ["id" => "20","name" => "Suprat","alamat" => "Jl. Melati No. 29","type" => "Peternak","keterangan" => "Elf"],
            ["id" => "21","name" => "Mamik","alamat" => "Jl. Melati No. 14","type" => "Peternak","keterangan" => "Elf"],
            ["id" => "22","name" => "Isnafuah","alamat" => "Jl. Melati No. 41","type" => "Peternak","keterangan" => "Elf"],
            ["id" => "23","name" => "Edi dawung","alamat" => "Jl. Melati No. 31","type" => "Peternak","keterangan" => "Elf"],
            ["id" => "24","name" => "Rohmad","alamat" => "Jl. Melati No. 48","type" => "Peternak","keterangan" => "Elf"],
            ["id" => "25","name" => "Sukar","alamat" => "Jl. Melati No. 8","type" => "Peternak","keterangan" => "Elf"],
            ["id" => "26","name" => "Imam Karangbendo","alamat" => "Jl. Melati No. 3","type" => "Peternak","keterangan" => "Elf"],
            ["id" => "27","name" => "Agus dawung","alamat" => "Jl. Melati No. 33","type" => "Peternak","keterangan" => "Elf"],
            ["id" => "28","name" => "Wardoyo","alamat" => "Jl. Melati No. 34","type" => "Peternak","keterangan" => "Elf"],
            ["id" => "29","name" => "Wiji","alamat" => "Jl. Melati No. 47","type" => "Peternak","keterangan" => "Elf"],
            ["id" => "30","name" => "Kaseri","alamat" => "Jl. Melati No. 3","type" => "Peternak","keterangan" => "Elf"],
            ["id" => "31","name" => "Samsul dayu","alamat" => "Jl. Melati No. 50","type" => "Peternak","keterangan" => "Elf"],
            ["id" => "32","name" => "Sunarman","alamat" => "Jl. Melati No. 1","type" => "Peternak","keterangan" => "Elf"],
            ["id" => "33","name" => " Elf","alamat" => "Jl. Melati No. 42","type" => "Peternak","keterangan" => "Elf"],
            ["id" => "34","name" => "Gunawan","alamat" => "Jl. Melati No. 43","type" => "Peternak","keterangan" => "Elf"],
            ["id" => "35","name" => "Purbo","alamat" => "Jl. Melati No. 13","type" => "Peternak","keterangan" => "Elf"],
            ["id" => "36","name" => "Yanto dawung","alamat" => "Jl. Melati No. 45","type" => "Peternak","keterangan" => "Elf"],
            ["id" => "37","name" => "Basuki","alamat" => "Jl. Melati No. 6","type" => "Peternak","keterangan" => "Elf"],
            ["id" => "38","name" => "Ika Karangbendo","alamat" => "Jl. Melati No. 35","type" => "Peternak","keterangan" => "Elf"],
            ["id" => "39","name" => "Ngari","alamat" => "Jl. Melati No. 29","type" => "Peternak","keterangan" => "Elf"],
            ["id" => "40","name" => "Naning","alamat" => "Jl. Melati No. 15","type" => "Peternak","keterangan" => "Elf"],
            ["id" => "41","name" => "Andri Karangbendo","alamat" => "Jl. Melati No. 27","type" => "Peternak","keterangan" => "Elf"],
            ["id" => "42","name" => "Rowi","alamat" => "Jl. Melati No. 8","type" => "Peternak","keterangan" => "Elf"],
            ["id" => "43","name" => "B Sun Candirejo","alamat" => "Jl. Melati No. 22","type" => "Peternak","keterangan" => "Elf"],
            ["id" => "44","name" => "Andri Kalicilik","alamat" => "Jl. Melati No. 49","type" => "Peternak","keterangan" => "Elf"],
            ["id" => "45","name" => "Ririd","alamat" => "Jl. Melati No. 16","type" => "Peternak","keterangan" => "Elf"],
            ["id" => "46","name" => "Suci Kuning","alamat" => "Jl. Kenanga No. 17","type" => "Peternak","keterangan" => "Kuning"],
            ["id" => "47","name" => "Topah","alamat" => "Jl. Kenanga No. 10","type" => "Peternak","keterangan" => "Kuning"],
            ["id" => "48","name" => "Joko Bonkakah","alamat" => "Jl. Kenanga No. 35","type" => "Peternak","keterangan" => "Kuning"],
            ["id" => "49","name" => "Suryono","alamat" => "Jl. Kenanga No. 31","type" => "Peternak","keterangan" => "Kuning"],
            ["id" => "50","name" => "Triono","alamat" => "Jl. Kenanga No. 36","type" => "Peternak","keterangan" => "Kuning"],
            ["id" => "51","name" => "Febri","alamat" => "Jl. Kenanga No. 15","type" => "Peternak","keterangan" => "Kuning"],
            ["id" => "52","name" => "Fadil","alamat" => "Jl. Kenanga No. 27","type" => "Peternak","keterangan" => "Kuning"],
            ["id" => "53","name" => "Kolik Ngiwak","alamat" => "Jl. Kenanga No. 34","type" => "Peternak","keterangan" => "Kuning"],
            ["id" => "54","name" => "Jam","alamat" => "Jl. Kenanga No. 21","type" => "Peternak","keterangan" => "Kuning"],
            ["id" => "55","name" => "Wulan","alamat" => "Jl. Kenanga No. 26","type" => "Peternak","keterangan" => "Kuning"],
            ["id" => "56","name" => "Leginah","alamat" => "Jl. Kenanga No. 3","type" => "Peternak","keterangan" => "Kuning"],
            ["id" => "57","name" => "Kholis","alamat" => "Jl. Kenanga No. 24","type" => "Peternak","keterangan" => "Kuning"],
            ["id" => "58","name" => "Septi","alamat" => "Jl. Kenanga No. 34","type" => "Peternak","keterangan" => "Kuning"],
            ["id" => "59","name" => "Arif Bonkakah","alamat" => "Jl. Kenanga No. 19","type" => "Peternak","keterangan" => "Kuning"],
            ["id" => "60","name" => "Yadi","alamat" => "Jl. Kenanga No. 18","type" => "Peternak","keterangan" => "Kuning"],
            ["id" => "61","name" => "Nurkholis Tawing","alamat" => "Jl. Kenanga No. 17","type" => "Peternak","keterangan" => "Kuning"],
            ["id" => "62","name" => "Karyo","alamat" => "Jl. Kenanga No. 36","type" => "Peternak","keterangan" => "Kuning"],
            ["id" => "63","name" => "Safii","alamat" => "Jl. Kenanga No. 33","type" => "Peternak","keterangan" => "Kuning"],
            ["id" => "64","name" => "Arifin Dermojayan","alamat" => "Jl. Kenanga No. 4","type" => "Peternak","keterangan" => "Kuning"],
            ["id" => "65","name" => "Irul Ringinanom","alamat" => "Jl. Kenanga No. 36","type" => "Peternak","keterangan" => "Kuning"],
            ["id" => "66","name" => "Tini","alamat" => "Jl. Kenanga No. 47","type" => "Peternak","keterangan" => "Kuning"],
            ["id" => "67","name" => "Didit","alamat" => "Jl. Kenanga No. 34","type" => "Peternak","keterangan" => "Kuning"],
            ["id" => "68","name" => "Daroini","alamat" => "Jl. Kenanga No. 13","type" => "Peternak","keterangan" => "Kuning"],
            ["id" => "69","name" => "Huda Ringinanom","alamat" => "Jl. Kenanga No. 21","type" => "Peternak","keterangan" => "Kuning"],
            ["id" => "70","name" => "Joko Manding","alamat" => "Jl. Kenanga No. 31","type" => "Peternak","keterangan" => "Kuning"],
            ["id" => "71","name" => "Kari","alamat" => "Jl. Kenanga No. 13","type" => "Peternak","keterangan" => "Kuning"],
            ["id" => "72","name" => "Saiful","alamat" => "Jl. Kenanga No. 38","type" => "Peternak","keterangan" => "Kuning"],
            ["id" => "73","name" => "Lim","alamat" => "Jl. Kenanga No. 41","type" => "Peternak","keterangan" => "Kuning"],
            ["id" => "74","name" => "Ghasa","alamat" => "Jl. Kenanga No. 40","type" => "Peternak","keterangan" => "Kuning"],
            ["id" => "75","name" => "Adi","alamat" => "Jl. Kenanga No. 12","type" => "Peternak","keterangan" => "Kuning"],
            ["id" => "76","name" => "Utami","alamat" => "Jl. Kenanga No. 33","type" => "Peternak","keterangan" => "Kuning"],
            ["id" => "77","name" => "Harmi","alamat" => "Jl. Kenanga No. 35","type" => "Peternak","keterangan" => "Kuning"],
            ["id" => "78","name" => "Tukiran","alamat" => "Jl. Kenanga No. 21","type" => "Peternak","keterangan" => "Kuning"],
            ["id" => "79","name" => "Suratman","alamat" => "Jl. Kenanga No. 49","type" => "Peternak","keterangan" => "Kuning"],
            ["id" => "80","name" => "Dwin","alamat" => "Jl. Kenanga No. 18","type" => "Peternak","keterangan" => "Kuning"],
            ["id" => "81","name" => "Koim","alamat" => "Jl. Kenanga No. 34","type" => "Peternak","keterangan" => "Kuning"],
            ["id" => "82","name" => "Kafid","alamat" => "Jl. Kenanga No. 20","type" => "Peternak","keterangan" => "Kuning"],
            ["id" => "83","name" => "Hanik","alamat" => "Jl. Kenanga No. 39","type" => "Peternak","keterangan" => "Kuning"],
            ["id" => "84","name" => "Pinka","alamat" => "Jl. Mawar No. 18","type" => "Peternak","keterangan" => "Merah"],
            ["id" => "85","name" => "Farida","alamat" => "Jl. Mawar No. 25","type" => "Peternak","keterangan" => "Merah"],
            ["id" => "86","name" => "Ngalimin","alamat" => "Jl. Mawar No. 19","type" => "Peternak","keterangan" => "Merah"],
            ["id" => "87","name" => "Karyani","alamat" => "Jl. Mawar No. 15","type" => "Peternak","keterangan" => "Merah"],
            ["id" => "88","name" => "Rudi bontoro","alamat" => "Jl. Mawar No. 35","type" => "Peternak","keterangan" => "Merah"],
            ["id" => "89","name" => "Ahmad","alamat" => "Jl. Mawar No. 15","type" => "Peternak","keterangan" => "Merah"],
            ["id" => "90","name" => "Wiroyo","alamat" => "Jl. Mawar No. 7","type" => "Peternak","keterangan" => "Merah"],
            ["id" => "91","name" => "Kasianto","alamat" => "Jl. Mawar No. 35","type" => "Peternak","keterangan" => "Merah"],
            ["id" => "92","name" => "Yanto Sukoanyar","alamat" => "Jl. Mawar No. 29","type" => "Peternak","keterangan" => "Merah"],
            ["id" => "93","name" => "Jumari","alamat" => "Jl. Mawar No. 18","type" => "Peternak","keterangan" => "Merah"],
            ["id" => "94","name" => "Rob","alamat" => "Jl. Mawar No. 12","type" => "Peternak","keterangan" => "Merah"],
            ["id" => "95","name" => "Sutik Sidomulyo","alamat" => "Jl. Mawar No. 26","type" => "Peternak","keterangan" => "Merah"],
            ["id" => "96","name" => "Fais","alamat" => "Jl. Mawar No. 17","type" => "Peternak","keterangan" => "Merah"],
            ["id" => "97","name" => "Nano","alamat" => "Jl. Mawar No. 35","type" => "Peternak","keterangan" => "Merah"],
            ["id" => "98","name" => "Sareh","alamat" => "Jl. Mawar No. 42","type" => "Peternak","keterangan" => "Merah"],
            ["id" => "99","name" => "Andi Batuaji","alamat" => "Jl. Mawar No. 5","type" => "Peternak","keterangan" => "Merah"],
            ["id" => "100","name" => "Aris Sidomulyo","alamat" => "Jl. Mawar No. 16","type" => "Peternak","keterangan" => "Merah"],
            ["id" => "101","name" => "Imam sidomulyo","alamat" => "Jl. Mawar No. 14","type" => "Peternak","keterangan" => "Merah"],
            ["id" => "102","name" => "Korib","alamat" => "Jl. Mawar No. 46","type" => "Peternak","keterangan" => "Merah"],
            ["id" => "103","name" => "Irul sidomulyo","alamat" => "Jl. Mawar No. 30","type" => "Peternak","keterangan" => "Merah"],
            ["id" => "104","name" => "Yuda puyuh","alamat" => "Jl. Mawar No. 37","type" => "Peternak","keterangan" => "Merah"],
            ["id" => "105","name" => "Luis","alamat" => "Jl. Mawar No. 7","type" => "Peternak","keterangan" => "Merah"],
            ["id" => "106","name" => "Sunarmi","alamat" => "Jl. Mawar No. 11","type" => "Peternak","keterangan" => "Merah"],
            ["id" => "107","name" => "Kolik sumbernanas","alamat" => "Jl. Mawar No. 14","type" => "Peternak","keterangan" => "Merah"],
            ["id" => "108","name" => "Edi selorejo","alamat" => "Jl. Mawar No. 19","type" => "Peternak","keterangan" => "Merah"],
            ["id" => "109","name" => "Erna sumberasri","alamat" => "Jl. Mawar No. 50","type" => "Peternak","keterangan" => "Merah"],
            ["id" => "110","name" => "Samirin","alamat" => "Jl. Mawar No. 44","type" => "Peternak","keterangan" => "Merah"],
            ["id" => "111","name" => "Yanto Sumberasri","alamat" => "Jl. Mawar No. 32","type" => "Peternak","keterangan" => "Merah"],
            ["id" => "112","name" => "Rotul","alamat" => "Jl. Mawar No. 25","type" => "Peternak","keterangan" => "Merah"],
            ["id" => "113","name" => "Faruq","alamat" => "Jl. Mawar No. 40","type" => "Peternak","keterangan" => "Merah"],
            ["id" => "114","name" => "Sukiro","alamat" => "Jl. Mawar No. 36","type" => "Peternak","keterangan" => "Merah"],
            ["id" => "115","name" => "Sunar","alamat" => "Jl. Mawar No. 21","type" => "Peternak","keterangan" => "Merah"],
            ["id" => "116","name" => "Jainal Karetan","alamat" => "Jl. Mawar No. 28","type" => "Peternak","keterangan" => "Merah"],
            ["id" => "117","name" => "Yaul","alamat" => "Jl. Mawar No. 46","type" => "Peternak","keterangan" => "Merah"],
            ["id" => "118","name" => "Dewi","alamat" => "Jl. Mawar No. 8","type" => "Peternak","keterangan" => "Merah"],
            ["id" => "119","name" => "Savio","alamat" => "Jl. Mawar No. 32","type" => "Peternak","keterangan" => "Merah"],
            ["id" => "120","name" => "Likah","alamat" => "Jl. Mawar No. 10","type" => "Peternak","keterangan" => "Merah"],
            ["id" => "121","name" => "Rif","alamat" => "Jl. Mawar No. 16","type" => "Peternak","keterangan" => "Merah"],
            ["id" => "122","name" => "Kusnun","alamat" => "Jl. Mawar No. 18","type" => "Peternak","keterangan" => "Merah"],
            ["id" => "123","name" => "Soniah","alamat" => "Jl. Mawar No. 40","type" => "Peternak","keterangan" => "Merah"],
            ["id" => "124","name" => "Slamet","alamat" => "Jl. Mawar No. 1","type" => "Peternak","keterangan" => "Merah"],
            ["id" => "125","name" => "P Sun Bebek","alamat" => "Jl. Mawar No. 3","type" => "Peternak","keterangan" => "Merah"],
            ["id" => "126","name" => "Nasik","alamat" => "Jl. Mawar No. 27","type" => "Peternak","keterangan" => "Merah"],
            ["id" => "127","name" => "Jainudin","alamat" => "Jl. Mawar No. 17","type" => "Peternak","keterangan" => "Merah"],
            ["id" => "128","name" => "Mufas","alamat" => "Jl. Mawar No. 30","type" => "Peternak","keterangan" => "Merah"],
            ["id" => "130","name" => "Toko Cangkring","alamat" => "Jl. Dahlia No. 46","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "131","name" => "Sutris faksin","alamat" => "Jl. Dahlia No. 50","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "132","name" => "Edi Subkhan","alamat" => "Jl. Dahlia No. 20","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "133","name" => "Pri sumberasri","alamat" => "Jl. Dahlia No. 33","type" => "Peternak","keterangan" => "Merah"],
            ["id" => "134","name" => "Gatot","alamat" => "Jl. Dahlia No. 2","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "135","name" => "Yusuf","alamat" => "Jl. Dahlia No. 29","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "136","name" => "Wahyu Dawung","alamat" => "Jl. Dahlia No. 25","type" => "Peternak","keterangan" => "Elf"],
            ["id" => "137","name" => "Mariono","alamat" => "Jl. Dahlia No. 28","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "138","name" => "Winarsih","alamat" => "Jl. Dahlia No. 5","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "139","name" => "Andi Jagoan","alamat" => "Jl. Dahlia No. 46","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "140","name" => "Triono kaligedok","alamat" => "Jl. Dahlia No. 34","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "141","name" => "Mad Candirejo","alamat" => "Jl. Dahlia No. 38","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "142","name" => "Anti","alamat" => "Jl. Dahlia No. 30","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "143","name" => "Kontiyah","alamat" => "Jl. Dahlia No. 28","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "144","name" => "Sus","alamat" => "Jl. Dahlia No. 9","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "145","name" => "Gawing","alamat" => "Jl. Dahlia No. 5","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "146","name" => "Samsul","alamat" => "Jl. Dahlia No. 19","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "147","name" => "Sokib rumah ternak","alamat" => "Jl. Dahlia No. 2","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "148","name" => "Bagio","alamat" => "Jl. Dahlia No. 46","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "149","name" => "Sutinah","alamat" => "Jl. Dahlia No. 12","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "150","name" => "Nanang Kalicilik","alamat" => "Jl. Dahlia No. 9","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "151","name" => "In toko","alamat" => "Jl. Dahlia No. 7","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "152","name" => "Mastur","alamat" => "Jl. Dahlia No. 18","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "153","name" => "Agung Kalicilik","alamat" => "Jl. Dahlia No. 17","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "155","name" => "Iqsan","alamat" => "Jl. Dahlia No. 34","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "156","name" => "Rindang","alamat" => "Jl. Dahlia No. 25","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "157","name" => "Nikmah","alamat" => "Jl. Dahlia No. 44","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "158","name" => "Ana","alamat" => "Jl. Dahlia No. 25","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "159","name" => "Nanang Rejoso","alamat" => "Jl. Dahlia No. 4","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "160","name" => "Siti Horen","alamat" => "Jl. Dahlia No. 45","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "161","name" => "Pom kulon (keluar)","alamat" => "Jl. Dahlia No. 11","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "162","name" => "Rurin","alamat" => "Jl. Dahlia No. 4","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "163","name" => "Erna Kalicilik","alamat" => "Jl. Dahlia No. 37","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "164","name" => "Kabib","alamat" => "Jl. Dahlia No. 12","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "165","name" => "Pom candi (keluar)","alamat" => "Jl. Dahlia No. 3","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "166","name" => "Kandang Puyuh Ngiwak","alamat" => "Jl. Flamboyan No. 39","type" => "Peternak","keterangan" => "Kandang"],
            ["id" => "167","name" => "Kandang Puyuh Sidomulyo","alamat" => "Jl. Flamboyan No. 19","type" => "Peternak","keterangan" => "Kandang"],
            ["id" => "168","name" => "Kandang bebek","alamat" => "Jl. Flamboyan No. 31","type" => "Peternak","keterangan" => "Kandang"],
            ["id" => "169","name" => "Kandang ayam","alamat" => "Jl. Flamboyan No. 38","type" => "Peternak","keterangan" => "Kandang"],
            ["id" => "170","name" => "Kandang kambing","alamat" => "Jl. Flamboyan No. 8","type" => "Peternak","keterangan" => "Kandang"],
            ["id" => "171","name" => "Nunur","alamat" => "Jl. Anggrek No. 35","type" => "Pedagang","keterangan" => null],
            ["id" => "172","name" => "Ali Nota","alamat" => "Jl. Anggrek No. 45","type" => "Pedagang","keterangan" => null],
            ["id" => "173","name" => "Prayit","alamat" => "Jl. Anggrek No. 1","type" => "Pedagang","keterangan" => null],
            ["id" => "174","name" => "Suci","alamat" => "Jl. Anggrek No. 6","type" => "Pedagang","keterangan" => null],
            ["id" => "175","name" => "Seneng","alamat" => "Jl. Anggrek No. 8","type" => "Pedagang","keterangan" => null],
            ["id" => "176","name" => "Syah","alamat" => "Jl. Teratai No. 32","type" => "Karyawan","keterangan" => "Karyawan Keliling"],
            ["id" => "177","name" => "Agung mburi","alamat" => "Jl. Teratai No. 30","type" => "Karyawan","keterangan" => "Karyawan keliling"],
            ["id" => "178","name" => "Tri","alamat" => "Jl. Teratai No. 15","type" => "Karyawan","keterangan" => "Karyawan Keliling"],
            ["id" => "179","name" => "Heji","alamat" => "Jl. Teratai No. 46","type" => "Karyawan","keterangan" => "Karyawan Keliling"],
            ["id" => "180","name" => "Arya","alamat" => "Jl. Teratai No. 17","type" => "Karyawan","keterangan" => "Karyawan Keliling"],
            ["id" => "181","name" => "Hebi","alamat" => "Jl. Teratai No. 13","type" => "Karyawan","keterangan" => "Karyawan Keliling"],
            ["id" => "182","name" => "Zikin","alamat" => "Jl. Teratai No. 47","type" => "Karyawan","keterangan" => "Karyawan Keliling"],
            ["id" => "183","name" => "Ipul Sopir","alamat" => "Jl. Teratai No. 13","type" => "Karyawan","keterangan" => ""],
            ["id" => "184","name" => "Imam karyawan","alamat" => "Jl. Teratai No. 47","type" => "Karyawan","keterangan" => "Karyawan Keliling"],
            ["id" => "185","name" => "Shodiq","alamat" => "Jl. Teratai No. 6","type" => "Karyawan","keterangan" => "Karyawan Keliling"],
            ["id" => "186","name" => "Rurin karyawan","alamat" => "Jl. Teratai No. 35","type" => "Karyawan","keterangan" => "Karyawan Keliling"],
            ["id" => "187","name" => "Muda","alamat" => "Jl. Teratai No. 41","type" => "Karyawan","keterangan" => "Karyawan Keliling"],
            ["id" => "188","name" => "Zubet","alamat" => "Jl. Teratai No. 30","type" => "Karyawan","keterangan" => "Karyawan Keliling"],
            ["id" => "189","name" => "Iwan karyawan chalinda","alamat" => "Jl. Teratai No. 26","type" => "Karyawan","keterangan" => "Karyawan Keliling"],
            ["id" => "190","name" => "Anton","alamat" => "Jl. Teratai No. 37","type" => "Karyawan","keterangan" => "Karyawan Keliling"],
            ["id" => "191","name" => "Eko","alamat" => "Jl. Teratai No. 43","type" => "Karyawan","keterangan" => "Karyawan Keliling"],
            ["id" => "192","name" => "Rafi","alamat" => "Jl. Teratai No. 40","type" => "Karyawan","keterangan" => "Karyawan Keliling"],
            ["id" => "193","name" => "Son","alamat" => "Jl. Teratai No. 23","type" => "Karyawan","keterangan" => "Karyawan Keliling"],
            ["id" => "194","name" => "Mursyid","alamat" => "Jl. Teratai No. 13","type" => "Karyawan","keterangan" => "Karyawan Keliling"],
            ["id" => "195","name" => "Rum","alamat" => "Jl. Teratai No. 34","type" => "Karyawan","keterangan" => "Karyawan Keliling"],
            ["id" => "196","name" => "Sopiyah","alamat" => "Jl. Teratai No. 27","type" => "Karyawan","keterangan" => "Karyawan Keliling"],
            ["id" => "197","name" => "Irul karyawan lama","alamat" => "Jl. Teratai No. 25","type" => "Karyawan","keterangan" => "Karyawan Keliling"],
            ["id" => "198","name" => "Yuyun","alamat" => "Jl. Teratai No. 10","type" => "Karyawan","keterangan" => "Karyawan Keliling"],
            ["id" => "199","name" => "Zamron cs","alamat" => "Jl. Teratai No. 32","type" => "Karyawan","keterangan" => "Karyawan Keliling"],
            ["id" => "200","name" => "Agung Kel","alamat" => "Jl. Teratai No. 35","type" => "Karyawan","keterangan" => "Karyawan Keliling"],
            ["id" => "201","name" => "OUT (Sokib)","alamat" => "Jl. Teratai No. 7","type" => "Karyawan","keterangan" => "Karyawan Keliling"],
            ["id" => "202","name" => "Din","alamat" => "Jl. Teratai No. 3","type" => "Karyawan","keterangan" => "Karyawan Keliling"],
            ["id" => "203","name" => "Koim 2","alamat" => "Jl. Cempaka No. 24","type" => "Karyawan","keterangan" => "Karyawan Lain"],
            ["id" => "204","name" => "Anak Yatim","alamat" => "Jl. Cempaka No. 6","type" => "Karyawan","keterangan" => "Karyawan Lain"],
            ["id" => "205","name" => "Didit 2","alamat" => "Jl. Cempaka No. 20","type" => "Karyawan","keterangan" => "Karyawan Lain"],
            ["id" => "206","name" => "Ela","alamat" => "Jl. Cempaka No. 5","type" => "Karyawan","keterangan" => "Karyawan Lain"],
            ["id" => "207","name" => "Sipon","alamat" => "Jl. Cempaka No. 7","type" => "Karyawan","keterangan" => "Karyawan Lain"],
            ["id" => "208","name" => "Yeni","alamat" => "Jl. Cempaka No. 33","type" => "Karyawan","keterangan" => "Karyawan Lain"],
            ["id" => "209","name" => "Ika\/Aris","alamat" => "Jl. Cempaka No. 29","type" => "Karyawan","keterangan" => "Karyawan Lain"],
            ["id" => "210","name" => "Supri Sopir","alamat" => "Jl. Cempaka No. 8","type" => "Karyawan","keterangan" => "Karyawan Lain"],
            ["id" => "211","name" => "Sipon titip","alamat" => "Jl. Cempaka No. 29","type" => "Karyawan","keterangan" => "Karyawan Lain"],
            ["id" => "212","name" => "Mun","alamat" => "Jl. Cempaka No. 33","type" => "Karyawan","keterangan" => "Karyawan Lain"],
            ["id" => "213","name" => "Binti paket","alamat" => "Jl. Cempaka No. 48","type" => "Karyawan","keterangan" => "Karyawan Lain"],
            ["id" => "214","name" => "Pertashop","alamat" => "Jl. Cempaka No. 11","type" => "Karyawan","keterangan" => "Karyawan Lain"],
            ["id" => "215","name" => "Polet","alamat" => "Jl. Cempaka No. 36","type" => "Karyawan","keterangan" => "Karyawan Lain"],
            ["id" => "216","name" => "Toko 2","alamat" => "Jl. Cempaka No. 43","type" => "Karyawan","keterangan" => "Karyawan Lain"],
            ["id" => "217","name" => "Azka","alamat" => "Jl. Cempaka No. 30","type" => "Karyawan","keterangan" => "Karyawan Lain"],
            ["id" => "218","name" => "Zulfa","alamat" => "Jl. Cempaka No. 12","type" => "Karyawan","keterangan" => "Karyawan Lain"],
            ["id" => "219","name" => "Kasan","alamat" => "Jl. Cempaka No. 46","type" => "Karyawan","keterangan" => "Karyawan Lain"],
            ["id" => "220","name" => "Joko","alamat" => "Jl. Cempaka No. 37","type" => "Karyawan","keterangan" => "Karyawan Lain"],
            ["id" => "221","name" => "Yoga","alamat" => "Jl. Cempaka No. 18","type" => "Karyawan","keterangan" => "Karyawan Lain"],
            ["id" => "222","name" => "Bagas","alamat" => "Jl. Cempaka No. 10","type" => "Karyawan","keterangan" => "Karyawan Lain"],
            ["id" => "223","name" => "Jun","alamat" => "Jl. Cempaka No. 17","type" => "Karyawan","keterangan" => "Karyawan Lain"],
            ["id" => "224","name" => "Eka","alamat" => "Jl. Cempaka No. 26","type" => "Karyawan","keterangan" => "Karyawan Lain"],
            ["id" => "225","name" => "Nasik karyawan","alamat" => "Jl. Cempaka No. 3","type" => "Karyawan","keterangan" => "Karyawan Lain"],
            ["id" => "226","name" => "Niam","alamat" => "Jl. Cempaka No. 26","type" => "Karyawan","keterangan" => "Karyawan Lain"],
            ["id" => "227","name" => "Mufas 2","alamat" => "Jl. Cempaka No. 37","type" => "Karyawan","keterangan" => "Karyawan Lain"],
            ["id" => "228","name" => "Suyoto","alamat" => "Jl. Cempaka No. 20","type" => "Karyawan","keterangan" => "Karyawan Lain"],
            ["id" => "229","name" => "Azka titip","alamat" => "Jl. Cempaka No. 21","type" => "Karyawan","keterangan" => "Karyawan Lain"],
            ["id" => "230","name" => "Kateni","alamat" => "Jl. Cempaka No. 24","type" => "Karyawan","keterangan" => "Karyawan Lain"],
            ["id" => "231","name" => "Ridwan","alamat" => "Jl. Cempaka No. 30","type" => "Karyawan","keterangan" => "Karyawan Lain"],
            ["id" => "232","name" => "Tray Diamond \/DM","alamat" => "Jl. Raflesia No. 39","type" => "Supplier","keterangan" => "Supplier"],
            ["id" => "233","name" => "Tray Super Buah \/SB","alamat" => "Jl. Raflesia No. 42","type" => "Supplier","keterangan" => "Supplier"],
            ["id" => "234","name" => "Tray Random","alamat" => "Jl. Raflesia No. 6","type" => "Supplier","keterangan" => "Supplier"],
            ["id" => "235","name" => "Obat SK","alamat" => "Jl. Raflesia No. 41","type" => "Supplier","keterangan" => "Supplier"],
            ["id" => "236","name" => "Obat Ponggok","alamat" => "Jl. Raflesia No. 39","type" => "Supplier","keterangan" => "Supplier"],
            ["id" => "237","name" => "Obat Random","alamat" => "Jl. Raflesia No. 7","type" => "Supplier","keterangan" => "Supplier"],
            ["id" => "238","name" => "Sentrat SK","alamat" => "Jl. Raflesia No. 14","type" => "Supplier","keterangan" => "Supplier"],
            ["id" => "239","name" => "Sentrat Ponggok","alamat" => "Jl. Raflesia No. 45","type" => "Supplier","keterangan" => "Supplier"],
            ["id" => "240","name" => "Sentrat Random","alamat" => "Jl. Raflesia No. 42","type" => "Supplier","keterangan" => "Supplier"],
            ["id" => "241","name" => "Bp.Supriyadi","alamat" => "Jl. Raflesia No. 25","type" => "Supplier","keterangan" => "Supplier"],
            ["id" => "242","name" => "Harun","alamat" => "Jl. Matahari No. 1","type" => "Peternak","keterangan" => "Pocok"],
            ["id" => "243","name" => "Jemangin","alamat" => "Jl. Sepatu No. 1","type" => "Peternak","keterangan" => "Ternak Keluar"],
            ["id" => "244","name" => "Bima Pratama Biru 1","alamat" => "AG 8796 UM","type" => "Truk","keterangan" => "Bp. Subakir"],
            ["id" => "245","name" => "Bima Pratama Biru 2","alamat" => "AG 8393 UL","type" => "Truk","keterangan" => "Bp. Supri Handoko"],
            ["id" => "246","name" => "Bima Pratama Orange 1","alamat" => "AG 8529 UL","type" => "Truk","keterangan" => "Bp. Joko"],
            ["id" => "247","name" => "Bima Pratama Orange 2","alamat" => "AG 8622 UL","type" => "Truk","keterangan" => "Bp. Yoga"],
            ["id" => "248","name" => "Bima Pratama Hijau 1","alamat" => "AG 8026 UL","type" => "Truk","keterangan" => "Bp. Kasan"],
            ["id" => "249","name" => "Bima Pratama Hijau 2","alamat" => "AG 8310 UL","type" => "Truk","keterangan" => "Bp. Aris Fermansyah"],
            ["id" => "250","name" => "Sofyan","alamat" => "","type" => "Pedagang","keterangan" => null],
            ["id" => "251","name" => "Ria","alamat" => "","type" => "Pedagang","keterangan" => null], 
            ["id" => "252","name" => "Ali Cicil","alamat" => "","type" => "Pedagang","keterangan" => null],
            ["id" => "257","name" => "Yanto Bacem","alamat" => "","type" => "Peternak","keterangan" => "Merah"],
            ["id" => "259","name" => "Sun Pakan","alamat" => "","type" => "Peternak","keterangan" => "Rumah"], 
            ["id" => "260","name" => "Mad","alamat" => "","type" => "Peternak","keterangan" => "Rumah"], 
            ["id" => "261","name" => "Makin","alamat" => "","type" => "Peternak","keterangan" => "Rumah"], 
            ["id" => "262","name" => "Nurkolis Asin","alamat" => "Tawing","type" => "Pedagang","keterangan" => "Pedagang"], 
            ["id" => "263","name" => "Trinel","alamat" => "Sidorejo","type" => "Pedagang","keterangan" => "Pedagang"], 
            ["id" => "264","name" => "Priyo","alamat" => "Sumberasri","type" => "Peternak","keterangan" => "Rumah Pocokan"], 
            ["id" => "265","name" => "Yaul Pocokan","alamat" => "Gentor","type" => "Peternak","keterangan" => "Rumah Pocokan"], 
            ["id" => "266","name" => "Rofik","alamat" => "Gentor","type" => "Peternak","keterangan" => "Rumah Pocokan"],
            ["id" => "267","name" => "Kios BP","alamat" => "Gembongan","type" => "Pedagang","keterangan" => "Pedagang"], 
            ["id" => "268","name" => "Fahriadi","alamat" => "Banjarmasin","type" => "Pedagang","keterangan" => "Pedagang"],
            ["id" => "269","name" => "Yayuk Sumber Jaya","alamat" => "Patok","type" => "Pedagang","keterangan" => "Pedagang"], 
            ["id" => "270","name" => "Azka Kucing","alamat" => "Gentor","type" => "Peternak","keterangan" => "Rumah"], 
            ["id" => "271","name" => "Suri","alamat" => "Sumberasri","type" => "Peternak","keterangan" => "Rumah Pocokan"], 
            ["id" => "272","name" => "Toyibin ","alamat" => "Bacem","type" => "Karyawan","keterangan" => "Sopir"],
            ["id" => "273","name" => "Rita","alamat" => "Candirejo","type" => "Peternak","keterangan" => "Kuning"],
            ["id" => "274","name" => "Soleh","alamat" => "Bacem","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "275","name" => "Amin","alamat" => "Ngiwak","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "276","name" => "Karotin","alamat" => "Kalicilik","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "277","name" => "Yenni","alamat" => "Gentor","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "278","name" => "Dion Srengat","alamat" => "Srengat","type" => "Peternak","keterangan" => "Rumah"], 
            ["id" => "279","name" => "Slamet Kandang","alamat" => "Ngiwak","type" => "Karyawan","keterangan" => "Kandang Puyuh"], 
            ["id" => "281","name" => "Imam Sumberasri","alamat" => "Sumberasri","type" => "Peternak","keterangan" => "Rumah Pocokan"], 
            ["id" => "282","name" => "Ira ","alamat" => "Sumberasri","type" => "Peternak","keterangan" => "Rumah Pocokan"],
            ["id" => "283","name" => "Iput","alamat" => "Sumberasri","type" => "Peternak","keterangan" => "Rumah Pocokan"],
            ["id" => "284","name" => "Suji","alamat" => "Sumberasri","type" => "Peternak","keterangan" => "Rumah Pocokan"],
            ["id" => "285","name" => "Bambang ","alamat" => "Sumberasri","type" => "Peternak","keterangan" => "Rumah Pocokan"],
            ["id" => "286","name" => "Gatri","alamat" => "Bontoro","type" => "Peternak","keterangan" => "Rumah Pocokan"], 
            ["id" => "287","name" => "Takim","alamat" => "Gentor","type" => "Peternak","keterangan" => "Rumah Pocokan"], 
            ["id" => "288","name" => "Didik","alamat" => "","type" => "Karyawan","keterangan" => "Karyawan Lainnya"],
            ["id" => "289","name" => "Yeni Pakan Pulsa Dll","alamat" => "","type" => "Karyawan","keterangan" => "Karyawan Lainnya"], 
            ["id" => "290","name" => "Togibin","alamat" => "","type" => "Karyawan","keterangan" => "Karyawan Lainnya"],
            ["id" => "292","name" => "Makrus","alamat" => "","type" => "Karyawan","keterangan" => "Karyawan Keliling"],
            ["id" => "293","name" => "Danang ","alamat" => "Slemanan","type" => "Karyawan","keterangan" => "Sopir"],
            ["id" => "294","name" => "Nanda","alamat" => "Kalicilik","type" => "Peternak","keterangan" => "Rumah"], 
            ["id" => "295","name" => "Ukir","alamat" => "Bedali","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "296","name" => "Sutowo","alamat" => "Bedali","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "297","name" => "Yoko","alamat" => "Bedali","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "298","name" => "Bagus \/ Ali Acong","alamat" => "Ngampel","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "299","name" => "Umi","alamat" => "Kalicilik","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "300","name" => "Ferdi Family","alamat" => "Ngiwak Candirejo","type" => "Peternak","keterangan" => "Rumah"], 
            ["id" => "301","name" => "Irul kel\/mburi","alamat" => "","type" => "Karyawan","keterangan" => "Karyawan Keliling"], 
            ["id" => "302","name" => "Hakim stok","alamat" => "","type" => "Karyawan","keterangan" => null], 
            ["id" => "303","name" => "Ilham stok","alamat" => "","type" => "Karyawan","keterangan" => null],
            ["id" => "304","name" => "Yani ","alamat" => "Dawung","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "305","name" => "Fila","alamat" => "Candirejo","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "306","name" => "Iwan Yayah","alamat" => "Candirejo","type" => "Pedagang","keterangan" => "Pedagang"],
            ["id" => "307","name" => "Yenni Etika","alamat" => "Gentor","type" => "Pedagang","keterangan" => "Pedagang"],
            ["id" => "308","name" => "Ari Tray","alamat" => "Blitar","type" => "Peternak","keterangan" => "Pembeli Tray"],
            ["id" => "309","name" => "Muhsin","alamat" => "Blitar","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "310","name" => "Har Sumberasri","alamat" => "Sumberasri","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "311","name" => "Rudi Kalicilik","alamat" => "Kalicilik","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "312","name" => "Sah Telur","alamat" => "Blitar","type" => "Pedagang","keterangan" => "Pedagang"],
            ["id" => "313","name" => "Nur Bentes","alamat" => "Bonduren","type" => "Pedagang","keterangan" => "Pedagang"],
            ["id" => "314","name" => "Kamat","alamat" => "Ngampel","type" => "Pedagang","keterangan" => "Pedagang"],
            ["id" => "315","name" => "Pak Pri","alamat" => "Bima Pratama","type" => "Karyawan","keterangan" => "Karyawan"], 
            ["id" => "316","name" => "Truk Jakartanan","alamat" => "Bima Pratama","type" => "Karyawan","keterangan" => "Karyawan"], 
            ["id" => "317","name" => "Lastri","alamat" => "Bacem","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "318","name" => "Son Sabrina","alamat" => "Ngiwak","type" => "Peternak","keterangan" => "Rumah"], 
            ["id" => "319","name" => "Irul Arab","alamat" => "Bontoro","type" => "Peternak","keterangan" => "Peternak"],
            ["id" => "320","name" => "Atok","alamat" => "Blitar","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "321","name" => "Arifin Bacem","alamat" => "Bacem","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "322","name" => "Samsudin Bontoro","alamat" => "Bontoro","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "323","name" => "Ida BK","alamat" => "Wates","type" => "Pedagang","keterangan" => "Pedagang"],
            ["id" => "324","name" => "Masduki","alamat" => "Gentor","type" => "Pedagang","keterangan" => "Pedagang"],
            ["id" => "325","name" => "Farhan","alamat" => "Ngiwak","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "326","name" => "Agung Bacem","alamat" => "Bacem","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "327","name" => "Gampang","alamat" => "Gentor","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "328","name" => "Rafi Nglegok","alamat" => "Nglegok","type" => "Pedagang","keterangan" => "Pedagang"],
            ["id" => "329","name" => "Hakim  Candirejo","alamat" => "Candirejo","type" => "Pedagang","keterangan" => "Pedagang"],
            ["id" => "330","name" => "Sutinah Ngasin","alamat" => "Bacem","type" => "Pedagang","keterangan" => "Pedagang"],
            ["id" => "331","name" => "Slamet Titip","alamat" => "Candirejo","type" => "Karyawan","keterangan" => "Karyawan"],
            ["id" => "332","name" => "Zairul","alamat" => "Krebet","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "334","name" => "Dian Bacem","alamat" => "Bacem","type" => "Pedagang","keterangan" => "Pedagang"],
            ["id" => "335","name" => "Piyik Tray","alamat" => "Bendosari","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "336","name" => "Sodik Bongkar","alamat" => "Ngampel","type" => "Peternak","keterangan" => "Rumah"], 
            ["id" => "337","name" => "Dwi Narmiah ","alamat" => "Bacem","type" => "Pedagang","keterangan" => "Pedagang"], 
            ["id" => "338","name" => "Ani","alamat" => "Sumberasri","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "339","name" => "Abdul Muin","alamat" => "Bacem","type" => "Pedagang","keterangan" => "Pedagang"],
            ["id" => "340","name" => "Bos","alamat" => "Bima Pratama","type" => "Pedagang","keterangan" => "Predagang"],
            ["id" => "341","name" => "Lili Karawang","alamat" => "Karawang","type" => "Pedagang","keterangan" => "Pedagang"],
            ["id" => "342","name" => "Rum Candirejo","alamat" => "Candirejo","type" => "Pedagang","keterangan" => "Pedagang"],
            ["id" => "343","name" => "Mukip Nuryanto","alamat" => "Gentor","type" => "Peternak","keterangan" => "Rumah "],
            ["id" => "344","name" => "Maksum","alamat" => "Candirejo","type" => "Peternak","keterangan" => "Rumah"], 
            ["id" => "345","name" => "Rohib","alamat" => "Candirejo","type" => "Karyawan","keterangan" => "Karyawan"], 
            ["id" => "346","name" => "SK Polet","alamat" => "Blitar","type" => "Supplier","keterangan" => null],
            ["id" => "347","name" => "Sodik Telur","alamat" => "Ngiwak","type" => "Pedagang","keterangan" => "Pedagang"],
            ["id" => "348","name" => "Aji","alamat" => "Rejoso","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "349","name" => "Mbok Sipon","alamat" => "Ngiwak","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "350","name" => "Sofyan Titipan diam","alamat" => "","type" => "Pedagang","keterangan" => null],
            ["id" => "351","name" => "Prayit Titipan diam","alamat" => "","type" => "Pedagang","keterangan" => null],
            ["id" => "352","name" => "Nunur Titipan","alamat" => "","type" => "Pedagang","keterangan" => null], 
            ["id" => "353","name" => "Ria Titipan diam","alamat" => "","type" => "Pedagang","keterangan" => null],
            ["id" => "354","name" => "Ilham","alamat" => "Csndirejo","type" => "Pedagang","keterangan" => "Pedagang"],
            ["id" => "355","name" => "Ivan","alamat" => "Kaligedok","type" => "Peternak","keterangan" => "Elf"],
            ["id" => "356","name" => "Asrofi","alamat" => "Ngiwak","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "357","name" => "Hana","alamat" => "Jombang","type" => "Pedagang","keterangan" => "Pedagang"], 
            ["id" => "358","name" => "Abdul Muin Pakan","alamat" => "Bacem","type" => "Peternak","keterangan" => "Rumah"], 
            ["id" => "359","name" => "Jainal Bacem","alamat" => "Bacem","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "360","name" => "Wahyu Pare","alamat" => "Pare","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "361","name" => "Mud AB Putih","alamat" => "Nglegok","type" => "Pedagang","keterangan" => "Pedagang"], 
            ["id" => "362","name" => "Rafi Pakan","alamat" => "Nglegok","type" => "Peternak","keterangan" => "Rumah"], 
            ["id" => "363","name" => "Sawah Karawang","alamat" => "Karawang","type" => "Karyawan","keterangan" => "Karyawan"],
            ["id" => "364","name" => "Wanto Wates","alamat" => "Wates","type" => "Peternak","keterangan" => "Rumah"], 
            ["id" => "365","name" => "Mun Pakan","alamat" => "Candirejo","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "366","name" => "Sandi","alamat" => "Selorejo","type" => "Peternak","keterangan" => "Kuning"],
            ["id" => "367","name" => "Tohir Pakan","alamat" => "Ngampel","type" => "Peternak","keterangan" => "Rumah"], 
            ["id" => "368","name" => "Yu Siti","alamat" => "Ngiwak","type" => "Pedagang","keterangan" => "Pedagang"],
            ["id" => "369","name" => "Sinta","alamat" => "Bacem","type" => "Pedagang","keterangan" => "Pedagang"],
            ["id" => "370","name" => "Pondok Amal","alamat" => "Blitar","type" => "Pedagang","keterangan" => "Pedagang"],
            ["id" => "371","name" => "Kios BP Retur","alamat" => "Gembongan","type" => "Pedagang","keterangan" => "Pedagang"], 
            ["id" => "372","name" => "Andik","alamat" => "Candirejo","type" => "Peternak","keterangan" => "Rumah"], 
            ["id" => "373","name" => "Arya Telur","alamat" => "Candirejo","type" => "Pedagang","keterangan" => "Pedagang"],
            ["id" => "374","name" => "Ilham Tray","alamat" => "Candirejo","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "375","name" => "TB Patok","alamat" => "Patok","type" => "Karyawan","keterangan" => "Karyawan"],
            ["id" => "376","name" => "Heri","alamat" => "Blitar","type" => "Peternak","keterangan" => "Rumah"], 
            ["id" => "377","name" => "Mursyid Pakan","alamat" => "Candirejo","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "378","name" => "Adib","alamat" => "Blitar","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "379","name" => "Widodo","alamat" => "Karangbendo","type" => "Peternak","keterangan" => "Elf"],
            ["id" => "380","name" => "Sudar","alamat" => "Sumbernanas","type" => "Pedagang","keterangan" => "Pedagang"], 
            ["id" => "381","name" => "Kios Pakan PBP","alamat" => "Candirejo","type" => "Peternak","keterangan" => "Rumah"], 
            ["id" => "382","name" => "Iqbal","alamat" => "Mbolorejo","type" => "Peternak","keterangan" => "Kuning"],
            ["id" => "383","name" => "Ambon ","alamat" => "Sby","type" => "Pedagang","keterangan" => "Pedagang"],
            ["id" => "384","name" => "Yuni","alamat" => "Bonkakah","type" => "Peternak","keterangan" => "Kuning"], 
            ["id" => "385","name" => "Muslimah","alamat" => "Sidorejo","type" => "Pedagang","keterangan" => "Pedagang"],
            ["id" => "386","name" => "Nurkholis Sumbernanas Tray","alamat" => "","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "387","name" => "Sutinah BK","alamat" => "Bacem","type" => "Pedagang","keterangan" => null],
            ["id" => "388","name" => "Rifa Kucing","alamat" => "Rejotangan","type" => "Peternak","keterangan" => null],
            ["id" => "389","name" => "Mamat Gentor","alamat" => "Gentor","type" => "Peternak","keterangan" => null], 
            ["id" => "390","name" => "Kim Krem","alamat" => "Malang","type" => "Pedagang","keterangan" => null],
            ["id" => "391","name" => "Aldi","alamat" => "Subontoro","type" => "Peternak","keterangan" => null],
            ["id" => "392","name" => "Pono","alamat" => "Ponggok","type" => "Peternak","keterangan" => null],
            ["id" => "393","name" => "Irul(kunteng)","alamat" => "Sidorejo","type" => "Pedagang","keterangan" => null],
            ["id" => "394","name" => "Sugianto Sidomulyo","alamat" => "Sidomulyo","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "395","name" => "Kamal","alamat" => "Wates","type" => "Pedagang","keterangan" => ""], 
            ["id" => "396","name" => "Habibi","alamat" => "Bontoro","type" => "Pedagang","keterangan" => null],
            ["id" => "398","name" => "Rifa Telur","alamat" => "Ngiwak","type" => "Pedagang","keterangan" => null],
            ["id" => "399","name" => "Sriono","alamat" => "Rejotangan","type" => "Pedagang","keterangan" => null],
            ["id" => "400","name" => "Tia","alamat" => "Bacem","type" => "Pedagang","keterangan" => null],
            ["id" => "401","name" => "Rifai Bacem","alamat" => "Bacem","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "402","name" => "Yasin Bontoro","alamat" => "Bontoro","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "403","name" => "Lilis Bok Glodak","alamat" => "","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "404","name" => "Mak Siti","alamat" => "","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "405","name" => "Didik Suruhwadang","alamat" => "Suruhwadang","type" => "Pedagang","keterangan" => null],
            ["id" => "406","name" => "Nur Bentes Pakan","alamat" => "Kebonduren","type" => "Peternak","keterangan" => null], 
            ["id" => "407","name" => "Edi Krebet","alamat" => "Krebet","type" => "Peternak","keterangan" => "Merah"],
            ["id" => "408","name" => "Redi","alamat" => "Bacem","type" => "Peternak","keterangan" => null],
            ["id" => "409","name" => "Antok Sopir","alamat" => "Wates","type" => "Pedagang","keterangan" => null],
            ["id" => "410","name" => "Suprihatin","alamat" => "Ngampel","type" => "Pedagang","keterangan" => null],
            ["id" => "411","name" => "Degan Kandang Kambing","alamat" => "Ngiwak","type" => "Karyawan","keterangan" => null], 
            ["id" => "412","name" => "Dian Tray","alamat" => "Bacem","type" => "Peternak","keterangan" => null],
            ["id" => "413","name" => "Rowi Tray","alamat" => "Ngiwak","type" => "Peternak","keterangan" => null],
            ["id" => "414","name" => "Huda Pakan Batuaji","alamat" => "Batuaji","type" => "Peternak","keterangan" => null], 
            ["id" => "415","name" => "Wiwik Blitar","alamat" => "Blitar","type" => "Pedagang","keterangan" => null],
            ["id" => "416","name" => "Toyibin Pakan","alamat" => "Bacem","type" => "Peternak","keterangan" => null], 
            ["id" => "417","name" => "Agus Krem","alamat" => "Pati","type" => "Pedagang","keterangan" => null],
            ["id" => "418","name" => "Yadi Pakan","alamat" => "Wates","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "419","name" => "Inul","alamat" => "Bacem","type" => "Pedagang","keterangan" => null],
            ["id" => "420","name" => "Daru","alamat" => "Kalicilik","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "421","name" => "Marini","alamat" => "","type" => "Pedagang","keterangan" => null], 
            ["id" => "422","name" => "Mursid ","alamat" => "","type" => "Pedagang","keterangan" => null], 
            ["id" => "423","name" => "Anton Peternak","alamat" => "Candirejo","type" => "Peternak","keterangan" => null],
            ["id" => "424","name" => "Bekky SK","alamat" => "Wonodadi","type" => "Peternak","keterangan" => null],
            ["id" => "425","name" => "Mama Ella Pakan","alamat" => "Candirejo","type" => "Peternak","keterangan" => null], 
            ["id" => "426","name" => "Lukman Tray","alamat" => "","type" => "Peternak","keterangan" => null],
            ["id" => "427","name" => "Datul krem","alamat" => "","type" => "Pedagang","keterangan" => null],
            ["id" => "428","name" => "Ipin Krebet","alamat" => "Krebet","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "429","name" => "Muklim","alamat" => "","type" => "Peternak","keterangan" => null], 
            ["id" => "430","name" => "Udin Pare","alamat" => "Pare","type" => "Pedagang","keterangan" => null],
            ["id" => "431","name" => "Evan","alamat" => "","type" => "Peternak","keterangan" => null], 
            ["id" => "432","name" => "Kalim","alamat" => "Sidorejo","type" => "Peternak","keterangan" => null],
            ["id" => "433","name" => "Rosidah","alamat" => "","type" => "Peternak","keterangan" => null], 
            ["id" => "434","name" => "Muslimah Ternak","alamat" => "","type" => "Peternak","keterangan" => null], 
            ["id" => "435","name" => "Sopiyah telur","alamat" => "","type" => "Pedagang","keterangan" => null],
            ["id" => "436","name" => "Rizal Pakan","alamat" => "","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "437","name" => "Dea imut","alamat" => "Ponggok","type" => "Pedagang","keterangan" => null],
            ["id" => "438","name" => "Wawan ","alamat" => "Rejotangan","type" => "Pedagang","keterangan" => null],
            ["id" => "439","name" => "Widodo Krem","alamat" => "Ponggok ","type" => "Pedagang","keterangan" => null],
            ["id" => "440","name" => "Jikin Telur","alamat" => "Gentor ","type" => "Pedagang","keterangan" => null],
            ["id" => "441","name" => "Mulyono","alamat" => "Ngiwak, Candirejo","type" => "Peternak","keterangan" => "Rumah"], 
            ["id" => "442","name" => "Kisworo ","alamat" => "","type" => "Pedagang","keterangan" => null], 
            ["id" => "443","name" => "Habibi Berau ","alamat" => "Berau Kalimantan","type" => "Pedagang","keterangan" => null], 
            ["id" => "444","name" => "Fuat ","alamat" => "Cangkring ","type" => "Pedagang","keterangan" => null],
            ["id" => "445","name" => "Tomi Pakan","alamat" => "Candirejo","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "446","name" => "Murji ","alamat" => "Bedali","type" => "Peternak","keterangan" => "Rumah"],
            ["id" => "447","name" => "Ujuk","alamat" => "","type" => "Pedagang","keterangan" => null], 
            ["id" => "449","name" => "Sanjaya","alamat" => "","type" => "Peternak","keterangan" => null], 
            ["id" => "450","name" => "Udin Penyok","alamat" => "Pare","type" => "Peternak","keterangan" => null],
            ["id" => "451","name" => "Wiwik","alamat" => "Blitar","type" => "Peternak","keterangan" => null],
            ["id" => "452","name" => "Panen Pak Muklim","alamat" => "Ngiwak","type" => "Karyawan","keterangan" => "Rumah"], 
            ["id" => "453","name" => "Agus Ngiwak","alamat" => "Ngiwak","type" => "Peternak","keterangan" => null],
            ["id" => "454","name" => "Sundarsih","alamat" => "","type" => "Peternak","keterangan" => "Rumah"],  
        ];

        foreach ($clients as $client) {
            Client::create([
                'id' => $client['id'],
                'name' => $client['name'],
                'alamat' => $client['alamat'],
                'type' => $client['type'],
                'keterangan' => $client['keterangan'],
            ]);
        }
    }
}